### ISSUE TITLE
.gitignore files on windows produce invalid regular expressions

### ISSUE THREAD

**Issue by bbsdddougla** [aleclarson/build-if-changed#9]
When using build-if-changed on windows, the glob patterns generated for ignores are invalid. For example, this .gitignore file produces the following error:

`// .gitignore`
`obj/`

`>SyntaxError: Invalid regular expression: /^(?:C:\myproj\bcat\obj\)$/: Unterminated group
0>    at new RegExp (<anonymous>)
0>    at matchAny (C:\Users\adude\AppData\Roaming\nvm\v10.18.1\node_modules\build-if-changed\node_modules\recrawl\lib\recrawl.js:87:32)
0>    at Object.createMatcher (C:\Users\adude\AppData\Roaming\nvm\v10.18.1\node_modules\build-if-changed\node_modules\recrawl\lib\recrawl.js:129:39)
0>    at GitIgnore.test (C:\Users\adude\AppData\Roaming\nvm\v10.18.1\node_modules\build-if-changed\lib\gitignore.js:46:39)
0>    at Object.opts.filter (C:\Users\adude\AppData\Roaming\nvm\v10.18.1\node_modules\build-if-changed\lib\cli.js:19:46)
0>    at opts.filter (C:\Users\adude\AppData\Roaming\nvm\v10.18.1\node_modules\build-if-changed\lib\index.js:15:25)
0>    at recrawl_1.crawl.enter.dir (C:\Users\adude\AppData\Roaming\nvm\v10.18.1\node_modules\build-if-changed\lib\index.js:20:34)
0>    at crawl (C:\Users\adude\AppData\Roaming\nvm\v10.18.1\node_modules\build-if-changed\node_modules\recrawl\lib\recrawl.js:62:25)
0>    at process._tickCallback (internal/process/next_tick.js:68:7)
0>    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)`

**Comment by albertominetti** [comment]
Same for me, does not work on Windows

**Comment by DarthSonic** [comment]
same for me
